name: RocksDB CI

on: [push, pull_request]

jobs:
  test:
    name: ${{ matrix.build }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        build: [Windows]
        include:
          - build: Windows
            os: windows-latest
            experimental: true
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          submodules: true
      - name: Install rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust || 'stable' }}
          target: ${{ matrix.target }}
          profile: minimal
          override: true
      - name: Install dependencies
        if: runner.os == 'Windows'
        run: git clone --config core.autocrlf=false https://github.com/llvm/llvm-project.git   
      - name: Run librocksdb-sys tests
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --manifest-path=librocksdb-sys/Cargo.toml
      - name: Run rocksdb tests
        uses: actions-rs/cargo@v1
        with:
          command: test
